#!/bin/bash

function runCmd {
    eval "$@" >/dev/null &
    PID=$!
    while $(kill -n 0 $PID 2> /dev/null)
    do
      sleep 2
    done
}

echo -e "\nInstalling Docker on remote agent"
echo -e "\nnameserver 8.8.8.8 >> /etc/resolv.conf"
eval "curl -sSL https://get.docker.com/ubuntu/ | sudo sh"

echo -e "\nInstalling Panamax remote agent/adapter"
eval "curl http://download.panamax.io/agent/qa/pmx-agent-install | sudo bash"
eval "cd ~/pmx-agent && ./pmx-agent init -adapter-type=$1 -api=$2 -agent-ip=$3"
