#!/bin/bash

echo -e "\nInstalling Docker on remote agent"
echo -e "\nnameserver 8.8.8.8 >> /etc/resolv.conf"
sudo apt-get -y update
sudo apt-get -y install curl
curl -sSL https://get.docker.com/ubuntu/ | sudo sh

echo -e "\nInstalling Panamax remote agent/adapter"
curl http://download.panamax.io/agent/pmx-agent-install | sudo bash
cd ~/pmx-agent && sudo ./pmx-agent init -adapter-type=$1 -api=$2 -agent-ip=$3

exit 0;
