#!/bin/bash

echo -e "\nInstalling panamax remote agent/adapter"

#set -e
set -x

for line in `cat`; do
   eval $line
done

ssh_key="id_agent.pem"
adapter_type="fleet"
adapter_ip=""

if [[ "$AGENT_FLEET_API" != "" ]]; then
    adapter_ip="http://$AGENT_FLEET_API:4001"
    adapter_type="fleet"
else
    adapter_ip="$AGENT_KUBER_API"
    adapter_type="kubernetes"	
fi

agent_private_key=`echo $AGENT_PRIVATE_KEY | base64 --decode`

echo -e "$agent_private_key" > $ssh_key
chmod 400 $ssh_key

echo -e "\nInstalling Docker on remote agent"
ssh -o StrictHostKeyChecking=no  -i $ssh_key root@$AGENT_PUBLIC_IP "echo -e \"\\nnameserver 8.8.8.8\" >> /etc/resolv.conf"
ssh -o StrictHostKeyChecking=no  -i $ssh_key root@$AGENT_PUBLIC_IP "curl -sSL https://get.docker.com/ubuntu/ | sudo sh"   > /dev/null 2>&1

echo -e "\nInstalling Panamax remote agent/adapter"
ssh -o StrictHostKeyChecking=no  -i $ssh_key root@$AGENT_PUBLIC_IP "curl http://download.panamax.io/agent/qa/pmx-agent-install | sudo bash  && sudo bash -c \"cd ~/pmx-agent && ./pmx-agent init -adapter-type=$adapter_type -api=$adapter_ip -agent-ip=$AGENT_PUBLIC_IP\""    > /dev/null 2>&1
ssh -o StrictHostKeyChecking=no  -i $ssh_key root@$AGENT_PUBLIC_IP "cat ~/pmx-agent/agent/panamax_agent_key" > agent_key
key="$(<agent_key)"
echo $key

echo -e "\nAdding remote target to panamax"
key=${key//$'\n'/}
remote_target_name=${REMOTE_TARGET_NAME:-$(cat /proc/sys/kernel/random/uuid)}
echo "{ \"name\" : \"$remote_target_name\", \"auth_blob\" : \"$key\" }" > post_data.json

cat post_data.json

docker0_ip=${DOCKER0_IP:-"172.17.42.1"}
api_port=${API_PORT:-3001}

curl -X POST \
     -H 'Content-Type:application/json' \
     -H 'Accept: application/json' \
     --data-binary @post_data.json  \
     http://${docker0_ip}:${api_port}/deployment_targets

echo -e "\nThe Panamax Remote Agent and Adapter are now installed on your Installer node ($AGENT_PUBLIC_IP)."
